// Mocks generated by Mockito 5.4.6 from annotations
// in romm_store/test/widgets/settings_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;
import 'dart:io' as _i8;
import 'dart:typed_data' as _i11;

import 'package:flutter/foundation.dart' as _i4;
import 'package:romm_store/core/emulator/linux_strategies/linux_environment_strategy.dart'
    as _i3;
import 'package:romm_store/core/romm/romm_models.dart' as _i5;
import 'package:romm_store/core/romm/romm_service.dart' as _i9;
import 'package:romm_store/core/storage/directory_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:shared_preferences/shared_preferences.dart' as _i10;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeStorageStatus_0 extends _i1.SmartFake implements _i2.StorageStatus {
  _FakeStorageStatus_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLinuxEnvironmentStrategy_1 extends _i1.SmartFake
    implements _i3.LinuxEnvironmentStrategy {
  _FakeLinuxEnvironmentStrategy_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeValueNotifier_2<T> extends _i1.SmartFake
    implements _i4.ValueNotifier<T> {
  _FakeValueNotifier_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRomMConfig_3 extends _i1.SmartFake implements _i5.RomMConfig {
  _FakeRomMConfig_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [DirectoryService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDirectoryService extends _i1.Mock implements _i2.DirectoryService {
  MockDirectoryService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get romsRootPath =>
      (super.noSuchMethod(
            Invocation.getter(#romsRootPath),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#romsRootPath),
            ),
          )
          as String);

  @override
  String get emulatorsRootPath =>
      (super.noSuchMethod(
            Invocation.getter(#emulatorsRootPath),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#emulatorsRootPath),
            ),
          )
          as String);

  @override
  String get linuxSyncPreset =>
      (super.noSuchMethod(
            Invocation.getter(#linuxSyncPreset),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#linuxSyncPreset),
            ),
          )
          as String);

  @override
  _i2.StorageStatus get status =>
      (super.noSuchMethod(
            Invocation.getter(#status),
            returnValue: _FakeStorageStatus_0(this, Invocation.getter(#status)),
          )
          as _i2.StorageStatus);

  @override
  bool get isSteamDeck =>
      (super.noSuchMethod(Invocation.getter(#isSteamDeck), returnValue: false)
          as bool);

  @override
  _i3.LinuxEnvironmentStrategy get activeLinuxEnvironment =>
      (super.noSuchMethod(
            Invocation.getter(#activeLinuxEnvironment),
            returnValue: _FakeLinuxEnvironmentStrategy_1(
              this,
              Invocation.getter(#activeLinuxEnvironment),
            ),
          )
          as _i3.LinuxEnvironmentStrategy);

  @override
  set romsRootPath(String? value) => super.noSuchMethod(
    Invocation.setter(#romsRootPath, value),
    returnValueForMissingStub: null,
  );

  @override
  set emulatorsRootPath(String? value) => super.noSuchMethod(
    Invocation.setter(#emulatorsRootPath, value),
    returnValueForMissingStub: null,
  );

  @override
  set linuxSyncPreset(String? value) => super.noSuchMethod(
    Invocation.setter(#linuxSyncPreset, value),
    returnValueForMissingStub: null,
  );

  @override
  set linuxPresetRootPath(String? value) => super.noSuchMethod(
    Invocation.setter(#linuxPresetRootPath, value),
    returnValueForMissingStub: null,
  );

  @override
  set status(_i2.StorageStatus? value) => super.noSuchMethod(
    Invocation.setter(#status, value),
    returnValueForMissingStub: null,
  );

  @override
  _i7.Future<String?> detectEmuDeckRoot() =>
      (super.noSuchMethod(
            Invocation.method(#detectEmuDeckRoot, []),
            returnValue: _i7.Future<String?>.value(),
          )
          as _i7.Future<String?>);

  @override
  _i7.Future<_i2.StorageStatus> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i7.Future<_i2.StorageStatus>.value(
              _FakeStorageStatus_0(this, Invocation.method(#initialize, [])),
            ),
          )
          as _i7.Future<_i2.StorageStatus>);

  @override
  _i7.Future<String> getDefaultBase() =>
      (super.noSuchMethod(
            Invocation.method(#getDefaultBase, []),
            returnValue: _i7.Future<String>.value(
              _i6.dummyValue<String>(
                this,
                Invocation.method(#getDefaultBase, []),
              ),
            ),
          )
          as _i7.Future<String>);

  @override
  _i7.Future<void> resetRomsRoot() =>
      (super.noSuchMethod(
            Invocation.method(#resetRomsRoot, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> resetEmulatorsRoot() =>
      (super.noSuchMethod(
            Invocation.method(#resetEmulatorsRoot, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> setLinuxSyncPreset(String? preset) =>
      (super.noSuchMethod(
            Invocation.method(#setLinuxSyncPreset, [preset]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> setLinuxPresetRoot(String? path) =>
      (super.noSuchMethod(
            Invocation.method(#setLinuxPresetRoot, [path]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  void loadEmulatorPathOverrides() => super.noSuchMethod(
    Invocation.method(#loadEmulatorPathOverrides, []),
    returnValueForMissingStub: null,
  );

  @override
  _i7.Future<void> setEmulatorPathOverride(String? emulatorId, String? path) =>
      (super.noSuchMethod(
            Invocation.method(#setEmulatorPathOverride, [emulatorId, path]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<String?> getEmulatorUrlOverride(String? emulatorId) =>
      (super.noSuchMethod(
            Invocation.method(#getEmulatorUrlOverride, [emulatorId]),
            returnValue: _i7.Future<String?>.value(),
          )
          as _i7.Future<String?>);

  @override
  _i7.Future<void> setEmulatorUrlOverride(String? emulatorId, String? url) =>
      (super.noSuchMethod(
            Invocation.method(#setEmulatorUrlOverride, [emulatorId, url]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  String? getEmulatorPathOverride(String? emulatorId) =>
      (super.noSuchMethod(
            Invocation.method(#getEmulatorPathOverride, [emulatorId]),
          )
          as String?);

  @override
  _i7.Future<void> setRomsRoot(String? path) =>
      (super.noSuchMethod(
            Invocation.method(#setRomsRoot, [path]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> setEmulatorsRoot(String? path) =>
      (super.noSuchMethod(
            Invocation.method(#setEmulatorsRoot, [path]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  bool platformSupportsArchive(String? platformSlug) =>
      (super.noSuchMethod(
            Invocation.method(#platformSupportsArchive, [platformSlug]),
            returnValue: false,
          )
          as bool);

  @override
  _i7.Future<String> getRomsDirectory() =>
      (super.noSuchMethod(
            Invocation.method(#getRomsDirectory, []),
            returnValue: _i7.Future<String>.value(
              _i6.dummyValue<String>(
                this,
                Invocation.method(#getRomsDirectory, []),
              ),
            ),
          )
          as _i7.Future<String>);

  @override
  _i7.Future<Set<String>> getAllDownloadedFileNames() =>
      (super.noSuchMethod(
            Invocation.method(#getAllDownloadedFileNames, []),
            returnValue: _i7.Future<Set<String>>.value(<String>{}),
          )
          as _i7.Future<Set<String>>);

  @override
  _i7.Future<Map<String, Set<String>>> getAllDownloadedFileNamesByPlatform() =>
      (super.noSuchMethod(
            Invocation.method(#getAllDownloadedFileNamesByPlatform, []),
            returnValue: _i7.Future<Map<String, Set<String>>>.value(
              <String, Set<String>>{},
            ),
          )
          as _i7.Future<Map<String, Set<String>>>);

  @override
  _i7.Future<String> getRomDirectory(_i5.Game? game) =>
      (super.noSuchMethod(
            Invocation.method(#getRomDirectory, [game]),
            returnValue: _i7.Future<String>.value(
              _i6.dummyValue<String>(
                this,
                Invocation.method(#getRomDirectory, [game]),
              ),
            ),
          )
          as _i7.Future<String>);

  @override
  _i7.Future<String> getRomFilePath(_i5.Game? game) =>
      (super.noSuchMethod(
            Invocation.method(#getRomFilePath, [game]),
            returnValue: _i7.Future<String>.value(
              _i6.dummyValue<String>(
                this,
                Invocation.method(#getRomFilePath, [game]),
              ),
            ),
          )
          as _i7.Future<String>);

  @override
  _i7.Future<String?> findExistingRomPath(
    _i5.Game? game, {
    _i2.FileSystemIndex? index,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#findExistingRomPath, [game], {#index: index}),
            returnValue: _i7.Future<String?>.value(),
          )
          as _i7.Future<String?>);

  @override
  _i7.Future<String?> resolveSevenZipPath() =>
      (super.noSuchMethod(
            Invocation.method(#resolveSevenZipPath, []),
            returnValue: _i7.Future<String?>.value(),
          )
          as _i7.Future<String?>);

  @override
  _i7.Future<String> getEmulatorDirectory(String? emulatorId) =>
      (super.noSuchMethod(
            Invocation.method(#getEmulatorDirectory, [emulatorId]),
            returnValue: _i7.Future<String>.value(
              _i6.dummyValue<String>(
                this,
                Invocation.method(#getEmulatorDirectory, [emulatorId]),
              ),
            ),
          )
          as _i7.Future<String>);

  @override
  _i7.Future<String> getEmulatorAppSupportDirectory(
    String? emulatorName, {
    String? platformSlug,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getEmulatorAppSupportDirectory,
              [emulatorName],
              {#platformSlug: platformSlug},
            ),
            returnValue: _i7.Future<String>.value(
              _i6.dummyValue<String>(
                this,
                Invocation.method(
                  #getEmulatorAppSupportDirectory,
                  [emulatorName],
                  {#platformSlug: platformSlug},
                ),
              ),
            ),
          )
          as _i7.Future<String>);

  @override
  _i7.Future<String> getEmulatorBiosDirectory(
    String? emulatorId, {
    String? platformSlug,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getEmulatorBiosDirectory,
              [emulatorId],
              {#platformSlug: platformSlug},
            ),
            returnValue: _i7.Future<String>.value(
              _i6.dummyValue<String>(
                this,
                Invocation.method(
                  #getEmulatorBiosDirectory,
                  [emulatorId],
                  {#platformSlug: platformSlug},
                ),
              ),
            ),
          )
          as _i7.Future<String>);

  @override
  _i7.Future<String> getEmulatorSystemDirectory(
    String? emulatorId, {
    String? platformSlug,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getEmulatorSystemDirectory,
              [emulatorId],
              {#platformSlug: platformSlug},
            ),
            returnValue: _i7.Future<String>.value(
              _i6.dummyValue<String>(
                this,
                Invocation.method(
                  #getEmulatorSystemDirectory,
                  [emulatorId],
                  {#platformSlug: platformSlug},
                ),
              ),
            ),
          )
          as _i7.Future<String>);

  @override
  _i7.Future<void> deleteEmulator(String? emulatorId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteEmulator, [emulatorId]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<String> getEmulatorExecutable(
    String? emulatorId,
    String? executableName,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getEmulatorExecutable, [
              emulatorId,
              executableName,
            ]),
            returnValue: _i7.Future<String>.value(
              _i6.dummyValue<String>(
                this,
                Invocation.method(#getEmulatorExecutable, [
                  emulatorId,
                  executableName,
                ]),
              ),
            ),
          )
          as _i7.Future<String>);

  @override
  _i7.Future<String?> findEmulatorExecutable(
    String? emulatorId,
    String? executableName,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#findEmulatorExecutable, [
              emulatorId,
              executableName,
            ]),
            returnValue: _i7.Future<String?>.value(),
          )
          as _i7.Future<String?>);

  @override
  _i7.Future<bool> isEmulatorInstalled(
    String? emulatorId,
    String? executableName,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#isEmulatorInstalled, [
              emulatorId,
              executableName,
            ]),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<bool> isRomDownloaded(_i5.Game? game) =>
      (super.noSuchMethod(
            Invocation.method(#isRomDownloaded, [game]),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  bool isEmuLaunchScript(String? path) =>
      (super.noSuchMethod(
            Invocation.method(#isEmuLaunchScript, [path]),
            returnValue: false,
          )
          as bool);

  @override
  _i7.Future<void> launchGame(
    _i5.Game? game,
    String? romPath,
    String? emulatorId,
    String? exePath, {
    List<String>? args = const [],
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #launchGame,
              [game, romPath, emulatorId, exePath],
              {#args: args},
            ),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<_i8.Process?> launchGameWithHandle(
    _i5.Game? game,
    String? romPath,
    String? emulatorId,
    String? exePath, {
    List<String>? args = const [],
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #launchGameWithHandle,
              [game, romPath, emulatorId, exePath],
              {#args: args},
            ),
            returnValue: _i7.Future<_i8.Process?>.value(),
          )
          as _i7.Future<_i8.Process?>);

  @override
  _i7.Future<void> launchStandalone(
    String? emulatorId,
    String? exePath, {
    List<String>? args = const [],
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #launchStandalone,
              [emulatorId, exePath],
              {#args: args},
            ),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> deleteRom(_i5.Game? game) =>
      (super.noSuchMethod(
            Invocation.method(#deleteRom, [game]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);
}

/// A class which mocks [RommService].
///
/// See the documentation for Mockito's code generation for more information.
class MockRommService extends _i1.Mock implements _i9.RommService {
  MockRommService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.ValueNotifier<bool> get isOffline =>
      (super.noSuchMethod(
            Invocation.getter(#isOffline),
            returnValue: _FakeValueNotifier_2<bool>(
              this,
              Invocation.getter(#isOffline),
            ),
          )
          as _i4.ValueNotifier<bool>);

  @override
  _i5.RomMConfig get config =>
      (super.noSuchMethod(
            Invocation.getter(#config),
            returnValue: _FakeRomMConfig_3(this, Invocation.getter(#config)),
          )
          as _i5.RomMConfig);

  @override
  String get authHeader =>
      (super.noSuchMethod(
            Invocation.getter(#authHeader),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#authHeader),
            ),
          )
          as String);

  @override
  void updateConfig(_i5.RomMConfig? newConfig) => super.noSuchMethod(
    Invocation.method(#updateConfig, [newConfig]),
    returnValueForMissingStub: null,
  );

  @override
  void startHeartbeat() => super.noSuchMethod(
    Invocation.method(#startHeartbeat, []),
    returnValueForMissingStub: null,
  );

  @override
  void stopHeartbeat() => super.noSuchMethod(
    Invocation.method(#stopHeartbeat, []),
    returnValueForMissingStub: null,
  );

  @override
  _i7.Future<void> refreshToken(_i10.SharedPreferences? prefs) =>
      (super.noSuchMethod(
            Invocation.method(#refreshToken, [prefs]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<_i5.Game?> getGame(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getGame, [id]),
            returnValue: _i7.Future<_i5.Game?>.value(),
          )
          as _i7.Future<_i5.Game?>);

  @override
  _i7.Future<List<_i5.Platform>> getPlatforms() =>
      (super.noSuchMethod(
            Invocation.method(#getPlatforms, []),
            returnValue: _i7.Future<List<_i5.Platform>>.value(<_i5.Platform>[]),
          )
          as _i7.Future<List<_i5.Platform>>);

  @override
  _i7.Future<List<Map<String, dynamic>>> getCollections() =>
      (super.noSuchMethod(
            Invocation.method(#getCollections, []),
            returnValue: _i7.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i7.Future<List<Map<String, dynamic>>>);

  @override
  String? resolveCoverUrl(_i5.Game? game) =>
      (super.noSuchMethod(Invocation.method(#resolveCoverUrl, [game]))
          as String?);

  @override
  _i7.Future<List<_i5.Game>> getGames(String? platformId) =>
      (super.noSuchMethod(
            Invocation.method(#getGames, [platformId]),
            returnValue: _i7.Future<List<_i5.Game>>.value(<_i5.Game>[]),
          )
          as _i7.Future<List<_i5.Game>>);

  @override
  _i7.Future<List<_i5.Game>> getAllGames({String? platformId}) =>
      (super.noSuchMethod(
            Invocation.method(#getAllGames, [], {#platformId: platformId}),
            returnValue: _i7.Future<List<_i5.Game>>.value(<_i5.Game>[]),
          )
          as _i7.Future<List<_i5.Game>>);

  @override
  _i7.Future<List<_i5.Game>> getRecentlyAdded({int? limit = 15}) =>
      (super.noSuchMethod(
            Invocation.method(#getRecentlyAdded, [], {#limit: limit}),
            returnValue: _i7.Future<List<_i5.Game>>.value(<_i5.Game>[]),
          )
          as _i7.Future<List<_i5.Game>>);

  @override
  _i7.Future<List<_i5.Game>> getRecentlyPlayed({int? limit = 15}) =>
      (super.noSuchMethod(
            Invocation.method(#getRecentlyPlayed, [], {#limit: limit}),
            returnValue: _i7.Future<List<_i5.Game>>.value(<_i5.Game>[]),
          )
          as _i7.Future<List<_i5.Game>>);

  @override
  _i7.Future<List<_i5.Game>> searchRoms({
    String? sha1,
    String? md5,
    String? search,
    String? platformId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#searchRoms, [], {
              #sha1: sha1,
              #md5: md5,
              #search: search,
              #platformId: platformId,
            }),
            returnValue: _i7.Future<List<_i5.Game>>.value(<_i5.Game>[]),
          )
          as _i7.Future<List<_i5.Game>>);

  @override
  _i7.Future<({List<_i5.Game> games, int total})> getGamesPage({
    int? offset = 0,
    int? limit = 50,
    String? platformId,
    String? search,
    List<String>? genres = const [],
    List<String>? regions = const [],
    List<String>? languages = const [],
    List<String>? collections = const [],
    List<String>? statuses = const [],
    bool? lastPlayed,
    bool? withCharIndex = false,
    bool? withFilterValues = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getGamesPage, [], {
              #offset: offset,
              #limit: limit,
              #platformId: platformId,
              #search: search,
              #genres: genres,
              #regions: regions,
              #languages: languages,
              #collections: collections,
              #statuses: statuses,
              #lastPlayed: lastPlayed,
              #withCharIndex: withCharIndex,
              #withFilterValues: withFilterValues,
            }),
            returnValue: _i7.Future<({List<_i5.Game> games, int total})>.value((
              games: <_i5.Game>[],
              total: 0,
            )),
          )
          as _i7.Future<({List<_i5.Game> games, int total})>);

  @override
  _i7.Future<_i5.Game?> getRandomGame() =>
      (super.noSuchMethod(
            Invocation.method(#getRandomGame, []),
            returnValue: _i7.Future<_i5.Game?>.value(),
          )
          as _i7.Future<_i5.Game?>);

  @override
  _i7.Future<List<_i5.SaveFile>> getSaves(String? gameId) =>
      (super.noSuchMethod(
            Invocation.method(#getSaves, [gameId]),
            returnValue: _i7.Future<List<_i5.SaveFile>>.value(<_i5.SaveFile>[]),
          )
          as _i7.Future<List<_i5.SaveFile>>);

  @override
  String getDownloadUrl(_i5.Game? game) =>
      (super.noSuchMethod(
            Invocation.method(#getDownloadUrl, [game]),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.method(#getDownloadUrl, [game]),
            ),
          )
          as String);

  @override
  _i7.Future<bool> uploadSave(
    String? gameId,
    _i8.File? saveFile, {
    String? slot,
    _i8.File? screenshotFile,
    String? overrideFilename,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #uploadSave,
              [gameId, saveFile],
              {
                #slot: slot,
                #screenshotFile: screenshotFile,
                #overrideFilename: overrideFilename,
              },
            ),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<bool> deleteSaves(List<int>? saveIds) =>
      (super.noSuchMethod(
            Invocation.method(#deleteSaves, [saveIds]),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<void> pruneOldSaves(String? gameId, {int? keepCount = 5}) =>
      (super.noSuchMethod(
            Invocation.method(
              #pruneOldSaves,
              [gameId],
              {#keepCount: keepCount},
            ),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<List<Map<String, dynamic>>> getSavesList(String? gameId) =>
      (super.noSuchMethod(
            Invocation.method(#getSavesList, [gameId]),
            returnValue: _i7.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i7.Future<List<Map<String, dynamic>>>);

  @override
  _i7.Future<Map<String, dynamic>?> getLatestSave(String? gameId) =>
      (super.noSuchMethod(
            Invocation.method(#getLatestSave, [gameId]),
            returnValue: _i7.Future<Map<String, dynamic>?>.value(),
          )
          as _i7.Future<Map<String, dynamic>?>);

  @override
  _i7.Future<_i11.Uint8List?> downloadSave(
    String? saveUrl, {
    _i10.SharedPreferences? prefs,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#downloadSave, [saveUrl], {#prefs: prefs}),
            returnValue: _i7.Future<_i11.Uint8List?>.value(),
          )
          as _i7.Future<_i11.Uint8List?>);

  @override
  _i7.Future<List<_i5.Firmware>> getFirmware({String? platformId}) =>
      (super.noSuchMethod(
            Invocation.method(#getFirmware, [], {#platformId: platformId}),
            returnValue: _i7.Future<List<_i5.Firmware>>.value(<_i5.Firmware>[]),
          )
          as _i7.Future<List<_i5.Firmware>>);

  @override
  String getFirmwareDownloadUrl(_i5.Firmware? firmware) =>
      (super.noSuchMethod(
            Invocation.method(#getFirmwareDownloadUrl, [firmware]),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.method(#getFirmwareDownloadUrl, [firmware]),
            ),
          )
          as String);

  @override
  _i7.Future<_i11.Uint8List?> downloadFirmware(
    _i5.Firmware? firmware, {
    void Function(int, int)? onProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #downloadFirmware,
              [firmware],
              {#onProgress: onProgress},
            ),
            returnValue: _i7.Future<_i11.Uint8List?>.value(),
          )
          as _i7.Future<_i11.Uint8List?>);

  @override
  _i7.Future<bool> updateRomProps(
    String? romId,
    _i10.SharedPreferences? prefs, {
    bool? backlogged,
    bool? nowPlaying,
    int? rating,
    String? status,
    int? completion,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateRomProps,
              [romId, prefs],
              {
                #backlogged: backlogged,
                #nowPlaying: nowPlaying,
                #rating: rating,
                #status: status,
                #completion: completion,
              },
            ),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<List<_i5.RomNote>> getRomNotes(String? romId) =>
      (super.noSuchMethod(
            Invocation.method(#getRomNotes, [romId]),
            returnValue: _i7.Future<List<_i5.RomNote>>.value(<_i5.RomNote>[]),
          )
          as _i7.Future<List<_i5.RomNote>>);

  @override
  _i7.Future<bool> createRomNote(
    String? romId,
    String? title,
    String? content,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createRomNote, [romId, title, content]),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<bool> deleteRomNote(String? romId, int? noteId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteRomNote, [romId, noteId]),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);
}
