// Mocks generated by Mockito 5.4.6 from annotations
// in romm_store/test/unit/strategy_registry_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:io' as _i7;

import 'package:romm_store/core/emulator/linux_strategies/linux_environment_strategy.dart'
    as _i3;
import 'package:romm_store/core/romm/romm_models.dart' as _i6;
import 'package:romm_store/core/storage/directory_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeStorageStatus_0 extends _i1.SmartFake implements _i2.StorageStatus {
  _FakeStorageStatus_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLinuxEnvironmentStrategy_1 extends _i1.SmartFake
    implements _i3.LinuxEnvironmentStrategy {
  _FakeLinuxEnvironmentStrategy_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [DirectoryService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDirectoryService extends _i1.Mock implements _i2.DirectoryService {
  MockDirectoryService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get romsRootPath =>
      (super.noSuchMethod(
            Invocation.getter(#romsRootPath),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#romsRootPath),
            ),
          )
          as String);

  @override
  String get emulatorsRootPath =>
      (super.noSuchMethod(
            Invocation.getter(#emulatorsRootPath),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#emulatorsRootPath),
            ),
          )
          as String);

  @override
  String get linuxSyncPreset =>
      (super.noSuchMethod(
            Invocation.getter(#linuxSyncPreset),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#linuxSyncPreset),
            ),
          )
          as String);

  @override
  _i2.StorageStatus get status =>
      (super.noSuchMethod(
            Invocation.getter(#status),
            returnValue: _FakeStorageStatus_0(this, Invocation.getter(#status)),
          )
          as _i2.StorageStatus);

  @override
  bool get isSteamDeck =>
      (super.noSuchMethod(Invocation.getter(#isSteamDeck), returnValue: false)
          as bool);

  @override
  _i3.LinuxEnvironmentStrategy get activeLinuxEnvironment =>
      (super.noSuchMethod(
            Invocation.getter(#activeLinuxEnvironment),
            returnValue: _FakeLinuxEnvironmentStrategy_1(
              this,
              Invocation.getter(#activeLinuxEnvironment),
            ),
          )
          as _i3.LinuxEnvironmentStrategy);

  @override
  set romsRootPath(String? value) => super.noSuchMethod(
    Invocation.setter(#romsRootPath, value),
    returnValueForMissingStub: null,
  );

  @override
  set emulatorsRootPath(String? value) => super.noSuchMethod(
    Invocation.setter(#emulatorsRootPath, value),
    returnValueForMissingStub: null,
  );

  @override
  set linuxSyncPreset(String? value) => super.noSuchMethod(
    Invocation.setter(#linuxSyncPreset, value),
    returnValueForMissingStub: null,
  );

  @override
  set linuxPresetRootPath(String? value) => super.noSuchMethod(
    Invocation.setter(#linuxPresetRootPath, value),
    returnValueForMissingStub: null,
  );

  @override
  set status(_i2.StorageStatus? value) => super.noSuchMethod(
    Invocation.setter(#status, value),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<String?> detectEmuDeckRoot() =>
      (super.noSuchMethod(
            Invocation.method(#detectEmuDeckRoot, []),
            returnValue: _i5.Future<String?>.value(),
          )
          as _i5.Future<String?>);

  @override
  _i5.Future<_i2.StorageStatus> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i5.Future<_i2.StorageStatus>.value(
              _FakeStorageStatus_0(this, Invocation.method(#initialize, [])),
            ),
          )
          as _i5.Future<_i2.StorageStatus>);

  @override
  _i5.Future<String> getDefaultBase() =>
      (super.noSuchMethod(
            Invocation.method(#getDefaultBase, []),
            returnValue: _i5.Future<String>.value(
              _i4.dummyValue<String>(
                this,
                Invocation.method(#getDefaultBase, []),
              ),
            ),
          )
          as _i5.Future<String>);

  @override
  _i5.Future<void> resetRomsRoot() =>
      (super.noSuchMethod(
            Invocation.method(#resetRomsRoot, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> resetEmulatorsRoot() =>
      (super.noSuchMethod(
            Invocation.method(#resetEmulatorsRoot, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> setLinuxSyncPreset(String? preset) =>
      (super.noSuchMethod(
            Invocation.method(#setLinuxSyncPreset, [preset]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> setLinuxPresetRoot(String? path) =>
      (super.noSuchMethod(
            Invocation.method(#setLinuxPresetRoot, [path]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void loadEmulatorPathOverrides() => super.noSuchMethod(
    Invocation.method(#loadEmulatorPathOverrides, []),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<void> setEmulatorPathOverride(String? emulatorId, String? path) =>
      (super.noSuchMethod(
            Invocation.method(#setEmulatorPathOverride, [emulatorId, path]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<String?> getEmulatorUrlOverride(String? emulatorId) =>
      (super.noSuchMethod(
            Invocation.method(#getEmulatorUrlOverride, [emulatorId]),
            returnValue: _i5.Future<String?>.value(),
          )
          as _i5.Future<String?>);

  @override
  _i5.Future<void> setEmulatorUrlOverride(String? emulatorId, String? url) =>
      (super.noSuchMethod(
            Invocation.method(#setEmulatorUrlOverride, [emulatorId, url]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  String? getEmulatorPathOverride(String? emulatorId) =>
      (super.noSuchMethod(
            Invocation.method(#getEmulatorPathOverride, [emulatorId]),
          )
          as String?);

  @override
  _i5.Future<void> setRomsRoot(String? path) =>
      (super.noSuchMethod(
            Invocation.method(#setRomsRoot, [path]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> setEmulatorsRoot(String? path) =>
      (super.noSuchMethod(
            Invocation.method(#setEmulatorsRoot, [path]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  bool platformSupportsArchive(String? platformSlug) =>
      (super.noSuchMethod(
            Invocation.method(#platformSupportsArchive, [platformSlug]),
            returnValue: false,
          )
          as bool);

  @override
  _i5.Future<String> getRomsDirectory() =>
      (super.noSuchMethod(
            Invocation.method(#getRomsDirectory, []),
            returnValue: _i5.Future<String>.value(
              _i4.dummyValue<String>(
                this,
                Invocation.method(#getRomsDirectory, []),
              ),
            ),
          )
          as _i5.Future<String>);

  @override
  _i5.Future<Set<String>> getAllDownloadedFileNames() =>
      (super.noSuchMethod(
            Invocation.method(#getAllDownloadedFileNames, []),
            returnValue: _i5.Future<Set<String>>.value(<String>{}),
          )
          as _i5.Future<Set<String>>);

  @override
  _i5.Future<Map<String, Set<String>>> getAllDownloadedFileNamesByPlatform() =>
      (super.noSuchMethod(
            Invocation.method(#getAllDownloadedFileNamesByPlatform, []),
            returnValue: _i5.Future<Map<String, Set<String>>>.value(
              <String, Set<String>>{},
            ),
          )
          as _i5.Future<Map<String, Set<String>>>);

  @override
  _i5.Future<String> getRomDirectory(_i6.Game? game) =>
      (super.noSuchMethod(
            Invocation.method(#getRomDirectory, [game]),
            returnValue: _i5.Future<String>.value(
              _i4.dummyValue<String>(
                this,
                Invocation.method(#getRomDirectory, [game]),
              ),
            ),
          )
          as _i5.Future<String>);

  @override
  _i5.Future<String> getRomFilePath(_i6.Game? game) =>
      (super.noSuchMethod(
            Invocation.method(#getRomFilePath, [game]),
            returnValue: _i5.Future<String>.value(
              _i4.dummyValue<String>(
                this,
                Invocation.method(#getRomFilePath, [game]),
              ),
            ),
          )
          as _i5.Future<String>);

  @override
  _i5.Future<String?> findExistingRomPath(
    _i6.Game? game, {
    _i2.FileSystemIndex? index,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#findExistingRomPath, [game], {#index: index}),
            returnValue: _i5.Future<String?>.value(),
          )
          as _i5.Future<String?>);

  @override
  _i5.Future<String?> resolveSevenZipPath() =>
      (super.noSuchMethod(
            Invocation.method(#resolveSevenZipPath, []),
            returnValue: _i5.Future<String?>.value(),
          )
          as _i5.Future<String?>);

  @override
  _i5.Future<String> getEmulatorDirectory(String? emulatorId) =>
      (super.noSuchMethod(
            Invocation.method(#getEmulatorDirectory, [emulatorId]),
            returnValue: _i5.Future<String>.value(
              _i4.dummyValue<String>(
                this,
                Invocation.method(#getEmulatorDirectory, [emulatorId]),
              ),
            ),
          )
          as _i5.Future<String>);

  @override
  _i5.Future<String> getEmulatorAppSupportDirectory(
    String? emulatorName, {
    String? platformSlug,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getEmulatorAppSupportDirectory,
              [emulatorName],
              {#platformSlug: platformSlug},
            ),
            returnValue: _i5.Future<String>.value(
              _i4.dummyValue<String>(
                this,
                Invocation.method(
                  #getEmulatorAppSupportDirectory,
                  [emulatorName],
                  {#platformSlug: platformSlug},
                ),
              ),
            ),
          )
          as _i5.Future<String>);

  @override
  _i5.Future<String> getEmulatorBiosDirectory(
    String? emulatorId, {
    String? platformSlug,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getEmulatorBiosDirectory,
              [emulatorId],
              {#platformSlug: platformSlug},
            ),
            returnValue: _i5.Future<String>.value(
              _i4.dummyValue<String>(
                this,
                Invocation.method(
                  #getEmulatorBiosDirectory,
                  [emulatorId],
                  {#platformSlug: platformSlug},
                ),
              ),
            ),
          )
          as _i5.Future<String>);

  @override
  _i5.Future<String> getEmulatorSystemDirectory(
    String? emulatorId, {
    String? platformSlug,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getEmulatorSystemDirectory,
              [emulatorId],
              {#platformSlug: platformSlug},
            ),
            returnValue: _i5.Future<String>.value(
              _i4.dummyValue<String>(
                this,
                Invocation.method(
                  #getEmulatorSystemDirectory,
                  [emulatorId],
                  {#platformSlug: platformSlug},
                ),
              ),
            ),
          )
          as _i5.Future<String>);

  @override
  _i5.Future<void> deleteEmulator(String? emulatorId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteEmulator, [emulatorId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<String> getEmulatorExecutable(
    String? emulatorId,
    String? executableName,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getEmulatorExecutable, [
              emulatorId,
              executableName,
            ]),
            returnValue: _i5.Future<String>.value(
              _i4.dummyValue<String>(
                this,
                Invocation.method(#getEmulatorExecutable, [
                  emulatorId,
                  executableName,
                ]),
              ),
            ),
          )
          as _i5.Future<String>);

  @override
  _i5.Future<String?> findEmulatorExecutable(
    String? emulatorId,
    String? executableName,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#findEmulatorExecutable, [
              emulatorId,
              executableName,
            ]),
            returnValue: _i5.Future<String?>.value(),
          )
          as _i5.Future<String?>);

  @override
  _i5.Future<bool> isEmulatorInstalled(
    String? emulatorId,
    String? executableName,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#isEmulatorInstalled, [
              emulatorId,
              executableName,
            ]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> isRomDownloaded(_i6.Game? game) =>
      (super.noSuchMethod(
            Invocation.method(#isRomDownloaded, [game]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  bool isEmuLaunchScript(String? path) =>
      (super.noSuchMethod(
            Invocation.method(#isEmuLaunchScript, [path]),
            returnValue: false,
          )
          as bool);

  @override
  _i5.Future<void> launchGame(
    _i6.Game? game,
    String? romPath,
    String? emulatorId,
    String? exePath, {
    List<String>? args = const [],
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #launchGame,
              [game, romPath, emulatorId, exePath],
              {#args: args},
            ),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i7.Process?> launchGameWithHandle(
    _i6.Game? game,
    String? romPath,
    String? emulatorId,
    String? exePath, {
    List<String>? args = const [],
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #launchGameWithHandle,
              [game, romPath, emulatorId, exePath],
              {#args: args},
            ),
            returnValue: _i5.Future<_i7.Process?>.value(),
          )
          as _i5.Future<_i7.Process?>);

  @override
  _i5.Future<void> launchStandalone(
    String? emulatorId,
    String? exePath, {
    List<String>? args = const [],
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #launchStandalone,
              [emulatorId, exePath],
              {#args: args},
            ),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> deleteRom(_i6.Game? game) =>
      (super.noSuchMethod(
            Invocation.method(#deleteRom, [game]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}
